server:
  port: 8088
  servlet:
    context-path: /community

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gdlgxy.lgcommunity.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: gw416416
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false

